### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [comaeio/LiveCloudKd#1]
I would like to point out that identifiers like “[`_HVDD_PARTITION`](https://github.com/comaeio/LiveCloudKd/blob/8c987c4abcac26200475e131678c6eeef16d6e0d/hvdd/hvdd.h#L61 "Update candidate")” and “[`_MAP_FILE`](https://github.com/comaeio/LiveCloudKd/blob/8c987c4abcac26200475e131678c6eeef16d6e0d/hvdd/hooker.h#L19 "Another update candidate")” [do eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by msuiche** [comment]
Windows Standard?
https://blogs.msdn.microsoft.com/oldnewthing/20080326-00/?p=22993

**Comment by elfring** [comment]
* Would you like to [reconsider the usage of (leading) underscores in these identifiers](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?")?
* How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?
